apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "stolon.proxy.fullname" . }}
  labels:
    app: {{ template "stolon.proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "stolon.proxy.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        component: proxy
        stolon-cluster: {{ template "stolon.clusterName" . }}
    spec:

{{- if .Values.proxy.affinity }}
      affinity:
{{ toYaml .Values.proxy.affinity | indent 8 }}
{{- end }}

{{- if .Values.proxy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.proxy.nodeSelector | indent 8 }}
{{- end }}

{{- if .Values.proxy.tolerations }}
      tolerations:
{{ toYaml .Values.proxy.tolerations | indent 8 }}
{{- end }}

      containers:
      - name: {{ template "stolon.proxy.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-proxy
        env:
          - name: STPROXY_CLUSTER_NAME
            value: {{ template "stolon.clusterName" . }}
          - name: STPROXY_STORE_BACKEND
            value: {{ .Values.store.backend | quote}}
          - name: STPROXY_KUBE_RESOURCE_KIND
            value: "configmap"
          - name: STPROXY_LISTEN_ADDRESS
            value: {{ default "0.0.0.0" .Values.proxy.listenAddress | quote }}
          - name: STSENTINEL_DEBUG
            value: {{ .Values.debug | quote}}
        ports:
          - containerPort: {{ .Values.ports.internalPort }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ports.internalPort }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.proxy.resources | indent 10 }}
